import EStyleSheet from "react-native-extended-stylesheet";
import { Colors, Fonts } from "../../../theme";

const styles = EStyleSheet.create({
  absolute: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
  },
  bgGradiant: {
    flex: 1,
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    right: 0,
  },
  modalCenteredView: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  modalBgImgStyle: {
    position: "absolute",
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
  },
  modalView: {
    overflow: "hidden",
    width: "100% - 56rem",
    backgroundColor: "#fff",
    borderRadius: "8rem",
    padding: "28rem",
    alignItems: "center",
    justifyContent: "center",
  },
  modalLocationBg: {
    width: "50rem",
    height: "50rem",
    borderRadius: "8rem",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    marginBottom: "42rem",
    shadowColor: Colors.lighterBlack,
    shadowOffset: {
      width: 0,
      height: "15rem",
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  modalLocationStyle: {
    width: "24rem",
    height: "30rem",
  },
  modalHeading: {
    textAlign: "center",
    lineHeight: "24rem",
    color: Colors.black,
    marginBottom: "25rem",
    fontSize: Fonts.size.h3,
    ...Fonts.style.blackText,
  },
  modalParegraph: {
    textAlign: "center",
    lineHeight: "20rem",
    color: Colors.black,
    opacity: 0.5,
    marginBottom: "31rem",
    fontSize: Fonts.size.regular,
    ...Fonts.style.normalText,
  },
  modalBtn: {
    paddingTop: "15rem",
    paddingBottom: "16rem",
    paddingHorizontal: "15rem",
    width: "100%",
    borderRadius: "8rem",
    backgroundColor: Colors.green,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  modalBtnIcon: {
    width: "16rem",
    height: "16rem",
  },
  modalBtnText: {
    lineHeight: "16rem",
    color: Colors.white,
    marginLeft: "14rem",
    fontSize: Fonts.size.regular,
    ...Fonts.style.blackText,
  },
  modalSearchLocationBtn: {
    backgroundColor: Colors.lighterGreen,
  },
  modalSearchLocationBtnText: {
    color: Colors.green,
  },
  orTextRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: "22rem",
  },
  orTextRowLine: {
    flex: 1,
    backgroundColor: Colors.gray,
    height: "1rem",
  },
  orText: {
    marginLeft: "12rem",
    marginRight: "13rem",
    color: Colors.lightBlack,
    lineHeight: "14rem",
    fontSize: Fonts.size.medium,
    ...Fonts.style.normalText,
  },
  searchLocationHeading: {
    textAlign: "left",
    marginBottom: "19rem",
    paddingRight: "20rem",
  },
  searchmodalView: {
    alignItems: "flex-start",
  },
  searchLocationGreenBtn: {
    marginTop: "19rem",
  },
  modalCloseBtn: {
    position: "absolute",
    right: "30rem",
    top: "34rem",
    width: "15rem",
    height: "15rem",
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseBtnIcon: {
    width: "12rem",
    height: "12rem",
  },
  savedAddressText: {
    lineHeight: "20rem",
    color: Colors.black,
    marginTop: "28rem",
    fontSize: Fonts.size.regular,
    ...Fonts.style.normalText,
  },
  saveAddressListRow: {
    marginTop: "19rem",
    width: "100%",
    borderBottomWidth: "1rem",
    borderColor: Colors.lighterBlack,
  },
  saveAddressText: {
    color: Colors.green,
    lineHeight: "16rem",
    paddingTop: "6rem",
    paddingBottom: "10rem",
    width: "100%",
    fontSize: Fonts.size.regular,
    ...Fonts.style.normalText,
  },
  saveAddressLabel: {
    color: Colors.green,
    lineHeight: "12rem",
    fontSize: Fonts.size.tiny,
    ...Fonts.style.extraBoldText,
  },
  map_top_details: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    minHeight: 40,
    position: "absolute",
    backgroundColor: "#fafafa",
    width: "95%",
    zIndex: 10,
    top: 10,
    alignContent: "center",
    alignSelf: "center",
    shadowOpacity: 1.0,
    borderRadius: 15,
    shadowColor: "#dddddd",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    elevation: 4,
  },
  input: {
    borderColor: Colors.lightGreen,
    borderWidth: 1,
    padding: 10,
    marginBottom: 10,
    fontWeight: "400",
  },
  button: {
    padding: 10,
    backgroundColor: Colors.lightGreen,
    marginTop: 15,
    fontWeight: "600",
    color: "#fff",
    textAlign: "center",
    fontSize: 15,
  },

  text: {
    color: Colors.black,
    fontWeight: "400",
    fontSize: 12,
    marginBottom: 5,
    textAlign: "left",
  },

  map_top_stripText: {
    width: "100%",
    padding: 10,
    color: Colors.gray,
    fontWeight: "500",
    fontSize: 12,
  },

  map_bottom_details: {
    justifyContent: "center",
    alignItems: "center",
    minHeight: 50,
    position: "absolute",
    backgroundColor: "#fafafa",
    width: "95%",
    zIndex: 3,
    bottom: 40,
    alignContent: "center",
    alignSelf: "center",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 5,
  },

  map_bottom_stripText: {
    width: "100%",
    padding: 10,
    color: Colors.black,
    fontWeight: "700",
    fontSize: 14,
    textAlignVertical: "center",
    textAlign: "center",
  },

  locateMe: {
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    width: 40,
    height: 40,
    backgroundColor: "#fff",
    borderRadius: 20,
    shadowOpacity: 1.0,
    shadowColor: "#dddddd",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    elevation: 4,
  },

  map: {
    ...EStyleSheet.absoluteFillObject,
  },
  marker: {
    zIndex: 19,
    position: "absolute",
    marginTop: -42,
    marginLeft: -14,
    left: "50%",
    top: "50%",
  },
  modalMainContainer: {
    backgroundColor: "#fff",
    minHeight: "20%",
    marginTop: "auto",
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    paddingBottom: 30,
    position: "relative",
  },
  modalInnerContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: 45,
    borderBottomColor: "#C4C4C4",
    borderBottomWidth: 1,
    width: "100%",
    paddingEnd: 20,
    paddingStart: 20,
  },
  enterAdrressTxt: {
    flex: 1,
    fontSize: 18,
    fontFamily: "SofiaPro",
    color: "#01000D",
  },
  closeBtn: {
    marginStart: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  inputText: {
    height: 45,
    borderColor: "#C4C4C4",
    borderWidth: 1,
    width: "100%",
    borderRadius: 10,
    fontFamily: "SofiaPro",
    padding: 10,
    marginBottom: 20,
    color: Colors.black,
  },
  confirmBtn: { width: "85%" },
  map_top_details: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    minHeight: 40,
    position: "absolute",
    backgroundColor: "#fff",
    width: "95%",
    zIndex: 0,
    top: 40,
    alignContent: "center",
    alignSelf: "center",
    shadowOpacity: 1,
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    elevation: 5,
    height: 55,
  },

  map_top_stripText: {
    width: "90%",
    padding: 10,
    color: Colors.black,
    fontWeight: "500",
    fontSize: 12,
    textAlign: "left",
    lineHeight: 17,
  },
  backBtn: {
    marginStart: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  addressBox: { width: "90%", marginStart: 10 },
  skeletonLineContainer: {
    flexDirection: "row",
    alignItems: "center",
    margin: 10,
  },
  saveAddressBtn: {
    borderColor: "#C4C4C4",
    borderWidth: 1,
    width: "100%",
    borderRadius: 10,
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#006653",
  },
  saveAddressTxt: { fontSize: 16, fontFamily: "SofiaPro", color: "#fff" },
  tagThisLocTxt: { fontSize: 10, fontFamily: "SofiaPro", color: "#01000D" },
  tagsContainer: { flexDirection: "row", paddingTop: 10 },
  tagsMainContainer: { paddingEnd: 20, paddingStart: 20, paddingTop: 15 },
  inputTxtContainer: {
    paddingEnd: 20,
    paddingStart: 20,
    width: "100%",
    paddingTop: 15,
    paddingBottom: 30,
  },
});

export default styles;
